<?php
    // generateId.php

    // Function to generate a unique alumni_id
    // Alumni ID is generated by concatenating programme, passout year, and a random 5-digit number
    function generateAlumniId($programme, $passoutYear, $connection) {
        // Set a limit on the number of attempts to generate a unique alumni_id
        $maxAttempts = 200;
        $attempts = 0;
           
        // Initialize $count to avoid undefined variable warning  r k 
        $count = 0;

        do {
            // Generate a random 5-digit number
            $randomDigits = str_pad(mt_rand(1, 99999), 5, '0', STR_PAD_LEFT);

            // Concatenate alumni_id parts
            $alumniId = $programme . $passoutYear . $randomDigits;
            
            // Check uniqueness in the database
            $checkQuery = "SELECT COUNT(*) FROM alumni_details WHERE alumni_id = ?";
            $checkStatement = $connection->prepare($checkQuery);
            $checkStatement->bind_param("s", $alumniId);
            $checkStatement->execute();
            $checkStatement->bind_result($count);  
            $checkStatement->fetch();

            // Break the loop if alumni_id is unique
            if ($count == 0) {
                $checkStatement->close();
                break;
            }

            // Close the statement after checking for existing alumni_id
            $checkStatement->close();

            // Increment attempts
            $attempts++;

        } while ($attempts < $maxAttempts);

        return $alumniId;
    }
?>
